name: S11 - DAST (ZAP)
on:
  workflow_dispatch:
  push:
    paths:
      - 'app/**'
      - '.github/workflows/ci-s11-dast.yml'

jobs:
  s11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure evidence dirs
        run: mkdir -p EVIDENCE/S11

      - name: Setup Python & run app
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8080 &
          APP_PID=$!
          echo "APP_PID=$APP_PID" >> $GITHUB_ENV

      - name: Wait for app to start
        run: |
          timeout 30 bash -c 'until curl -sf http://localhost:8080/healthz; do sleep 2; done'
          echo "App is ready!"

      - name: ZAP Baseline Scan
        run: |
          docker run --rm \
            --network host \
            -v "$PWD/EVIDENCE/S11:/zap/wrk:rw" \
            owasp/zap2docker-stable zap-baseline.py \
            -t http://localhost:8080 \
            -r /zap/wrk/zap_baseline.html \
            -J /zap/wrk/zap_baseline.json \
            -x /zap/wrk/zap_baseline.xml \
            -d

      - name: Verify ZAP reports
        run: |
          echo "Checking EVIDENCE/S11 contents:"
          ls -la EVIDENCE/S11/
          echo "File sizes:"
          find EVIDENCE/S11/ -name "*.html" -o -name "*.json" -o -name "*.xml" | xargs ls -lh

      - name: Stop the application
        if: always()
        run: |
          pkill -f "uvicorn app.main:app" || true

      - uses: actions/upload-artifact@v4
        with:
          name: S11_EVIDENCE
          path: EVIDENCE/S11
